Setting up linters and other files
mfadhili/portfolio pull request #1
Opened 2022-09-23 10:04 UTC by mfadhili

2022-09-24 00:29 UTC, jerryowusu reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a description or short summary describing the changes you are making in details. Kindly provide a description and a short summary.

![Screenshot from 2022-09-24 00-28-31](https://user-images.githubusercontent.com/65233860/192072159-f01960e3-4d64-4eee-a624-10ada4a7cd98.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-24 04:34 UTC, emmiiorji requested changes
Hi @mfadhili, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![a little more](https://user-images.githubusercontent.com/20554583/192079543-2ba2a4f6-33a3-41ef-840f-75945afbf233.gif)


## Good Highlights✔

- Linter checks are passing
- Adherence to GitHub flow
- Description for pull request has been added


## Required Changes ♻️

- Kindly ensure that you follow the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) to complete the sections (including styling) required for the current milestone. The to sections expected are the toolbar (or header) and the headline section (right after the header). You seem to have added sections that are meant to be in a future milestone.

Your current design:
![image](https://user-images.githubusercontent.com/20554583/192080028-e382f93e-97b5-4b0b-9b34-26adab40c395.png)

Your chosen design template:
![image](https://user-images.githubusercontent.com/20554583/192080142-1eb250ff-7c6f-4010-9b5b-34496dd05f91.png)


- _Check the comments under the review for more comments._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 04:34 UTC, emmiiorji commented on index.html
> +    <link rel="stylesheet" hrefv="./css/main.css">
You seem not to have linked your CSS properly by making a mistake with the name for the href attribute. Kindly correct this from `hrefv` and not `href`

2022-09-24 04:34 UTC, emmiiorji commented on index.html
> +
Kindly endeavour to specify appropriate `alt` attributes for your images. This is what the user sees whenever the image happens not to load properly.

2022-09-24 04:34 UTC, emmiiorji commented on css/main.css
> +body { background-color: darkkhaki; }
Kindly add styles to the project to make it match your chosen design. This milestone includes that.

2022-09-24 04:34 UTC, emmiiorji commented on .vscode/settings.json
> +}
I recommend that you ignore the .vscode directory as a best practice since it's only a local setup for your code editor.

2022-09-24 04:34 UTC, emmiiorji commented on README.md
Kindly add an MIT license file with the name LICENSE file to the root directory of your project in order not to have an inactive link.

2022-09-24 22:23 UTC, christianbiring1 approved these changes
Hi @mfadhili , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
![imageswelljob](https://user-images.githubusercontent.com/97100091/192120661-33c78294-8664-45bf-b238-af47e64dc2fb.jpeg)

## Highlights
- [ ] All linters are passing
- [ ] Repos is documented professionally.

## Optional suggestions
- [ ] I highly recommend you take into consideration those comments with the [OPTIONAL] flag as they will help take your project to the next level
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 22:23 UTC, christianbiring1 commented on index.html
> +                                <img src="/images/Card/Img Plaholder.svg" alt="Placeholder">
[OPTIONAL] 
- [ ] Kindly make sure you use the correct path for your images as you can see they are not displaying correctly.
`hint: you can remove the space between the name you gave your images`

2022-09-24 22:23 UTC, christianbiring1 commented on index.html
> +                                <img src="/images/Card/Img Plaholder.svg" alt="Placeholder">
[OPTIONAL] 
- [ ] Kindly make sure you use the correct path for your images as you can see they are not displaying correctly.
`hint: you can remove the space between the name you gave your images`

2022-09-24 22:23 UTC, christianbiring1 commented on index.html
> +                                <img src="/images/Card/Img Plaholder.svg" alt="Placeholder">
[OPTIONAL] 
- [ ] Kindly make sure you use the correct path for your images as you can see they are not displaying correctly.
`hint: you can remove the space between the name you gave your images`

2022-09-24 22:23 UTC, christianbiring1 commented on index.html
> +                                <img src="/images/Card/Img Plaholder.svg" alt="Placeholder">
[OPTIONAL] 
- [ ] Kindly make sure you use the correct path for your images as you can see they are not displaying correctly.
`hint: you can remove the space between the name you gave your images`

2022-09-24 22:30 UTC, Alfredbis29 requested changes
Hi @mfadhili , 

Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
![so close](https://user-images.githubusercontent.com/65233860/191304898-005dcfd5-2327-4feb-ad61-72caa0a0b874.gif) 

## Highlights
 * Your GitHub flow is correct :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* Project working correctly :heavy_check_mark:

 ## Required Changes 

 _Check the comments under the review._

 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 22:30 UTC, Alfredbis29 commented on css/main.css
> +
- [ ] Good job thus far, however, there is something you need to fix in order for your project to look fantastic, but you are almost there, as we copy the Figma design and if we compare your design to the Figma design, there are differences. Please update your design for a good vision :wink: 
Your Design :point_down: 
![masta](https://user-images.githubusercontent.com/88894525/192120613-dba767c5-fffc-4d9c-9abb-7f51b9a1e575.png)

Figma Design :point_down: 
![mastafigma](https://user-images.githubusercontent.com/88894525/192120630-6eabe69e-b707-4ed0-a6e0-687fbca37481.png)

2022-09-24 22:30 UTC, Alfredbis29 commented on index.html
> +        </div>
- [ ] The logo (if the design has one) is on the left and has a link `a` tag not a `p` tag , kindly change this for a good convention reason :wink:

2022-09-24 22:56 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @mfadhili , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 22:56 UTC, bobb-Rob commented on index.html
> +            <a class="welcome__text">Welcome</a>
- [ ] You have an `a` tag without the attribute `href` that holds the path to visit upon click. Kindly fix this

2022-09-24 23:43 UTC, Alfredbis29 commented
> Hi @mfadhili,
> 
> # Status: Changes Required 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ![a little more](https://user-images.githubusercontent.com/20554583/192079543-2ba2a4f6-33a3-41ef-840f-75945afbf233.gif) [ ![a little more](https://user-images.githubusercontent.com/20554583/192079543-2ba2a4f6-33a3-41ef-840f-75945afbf233.gif) ](https://user-images.githubusercontent.com/20554583/192079543-2ba2a4f6-33a3-41ef-840f-75945afbf233.gif) [ ](https://user-images.githubusercontent.com/20554583/192079543-2ba2a4f6-33a3-41ef-840f-75945afbf233.gif)
> 
> ## Good Highlights
> * Linter checks are passing
> * Adherence to GitHub flow
> * Description for pull request has been added
> 
> ## Required Changes 
> * Kindly ensure that you follow the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md) to complete the sections (including styling) required for the current milestone. The to sections expected are the toolbar (or header) and the headline section (right after the header). You seem to have added sections that are meant to be in a future milestone.
> 
> Your current design: ![image](https://user-images.githubusercontent.com/20554583/192080028-e382f93e-97b5-4b0b-9b34-26adab40c395.png)
> 
> Your chosen design template: ![image](https://user-images.githubusercontent.com/20554583/192080142-1eb250ff-7c6f-4010-9b5b-34496dd05f91.png)
> 
> * _Check the comments under the review for more comments._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-26 14:34 UTC, roshan-bajgain approved these changes
Hi @mfadhili, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions
- [ ] I would suggest that you create a new pull request next time. So It will be easier for the reviewer to review the project.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 07:30 UTC, merged